const ON_GAME_CREATED_EVENT = "ON_GAME_CREATED_EVENT";
const ON_GAME_AWAITING_EVENT = "ON_GAME_AWAITING_EVENT";
const ON_GAME_PLAYING_EVENT = "ON_GAME_PLAYING_EVENT";
const ON_SSE_TESTING_EVENT = "ON_SSE_TESTING_EVENT";
const ON_PARTICIPANT_JOINED = "ON_PARTICIPANT_JOINED";
const ON_PARTICIPANT_EXITED = "ON_PARTICIPANT_EXITED";

module.exports = {
    ON_GAME_CREATED_EVENT,
    ON_GAME_AWAITING_EVENT,
    ON_GAME_PLAYING_EVENT,
    ON_SSE_TESTING_EVENT,
    ON_PARTICIPANT_JOINED,
    ON_PARTICIPANT_EXITED,
}