const ON_GAME_CREATED_EVENT = "ON_GAME_CREATED_EVENT";
const ON_GAME_ACCEPTING_EVENT = "ON_GAME_ACCEPTING_EVENT";
const ON_GAME_PLAYING_EVENT = "ON_GAME_PLAYING_EVENT";
const ON_GAME_DELETED_EVENT = "ON_GAME_DELETED_EVENT";
const ON_SSE_TESTING_EVENT = "ON_SSE_TESTING_EVENT";
const ON_PARTICIPANT_JOINED = "ON_PARTICIPANT_JOINED";
const ON_PARTICIPANT_EXITED = "ON_PARTICIPANT_EXITED";
const GAME_STATUS_CREATED = "Created";
const GAME_STATUS_ACCEPTING = "Accepting";
const GAME_STATUS_PLAYING = "Playing";

module.exports = {
    ON_GAME_CREATED_EVENT,
    ON_GAME_ACCEPTING_EVENT,
    ON_GAME_PLAYING_EVENT,
    ON_GAME_DELETED_EVENT,
    ON_SSE_TESTING_EVENT,
    ON_PARTICIPANT_JOINED,
    ON_PARTICIPANT_EXITED,
    GAME_STATUS_CREATED,
    GAME_STATUS_ACCEPTING,
    GAME_STATUS_PLAYING,
}