const ON_GAME_CREATED_EVENT = "ON_GAME_CREATED_EVENT";
const ON_GAME_ACCEPTING_EVENT = "ON_GAME_ACCEPTING_EVENT";
const ON_GAME_PLAYING_EVENT = "ON_GAME_PLAYING_EVENT";
const ON_GAME_DELETED_EVENT = "ON_GAME_DELETED_EVENT";
const ON_SSE_TESTING_EVENT = "ON_SSE_TESTING_EVENT";
const ON_PARTICIPANT_JOINED = "ON_PARTICIPANT_JOINED";
const ON_PARTICIPANT_EXITED = "ON_PARTICIPANT_EXITED";
const GAME_STATUS_CREATED = "Created";
const GAME_STATUS_ACCEPTING = "Accepting";
const GAME_STATUS_PLAYING = "Playing";
const ON_GAME_STARTING_EVENT = "ON_GAME_STARTING_EVENT";
const ON_GAME_ENDING_EVENT = "ON_GAME_ENDING_EVENT";
const ON_BEFORE_QUESTION_EVENT = "ON_BEFORE_QUESTION_EVENT";
const ON_QUESTION_POSTED_EVENT = "ON_QUESTION_POSTED_EVENT";
const ON_ANSWER_POSTED_EVENT = "ON_ANSWER_POSTED_EVENT";
const ON_AFTER_QUESTION_EVENT = "ON_AFTER_QUESTION_EVENT";
const ON_BREAK_STARTING_EVENT = "ON_BREAK_STARTING_EVENT";
const ON_SNACK_BREAK_EVENT = "ON_SNACK_BREAK_EVENT";
const ON_BREAK_ENDING_EVENT = "ON_BREAK_ENDING_EVENT";

module.exports = {
    ON_GAME_CREATED_EVENT,
    ON_GAME_ACCEPTING_EVENT,
    ON_GAME_PLAYING_EVENT,
    ON_GAME_DELETED_EVENT,
    ON_SSE_TESTING_EVENT,
    ON_PARTICIPANT_JOINED,
    ON_PARTICIPANT_EXITED,
    GAME_STATUS_CREATED,
    GAME_STATUS_ACCEPTING,
    GAME_STATUS_PLAYING,
    ON_GAME_STARTING_EVENT,
    ON_GAME_ENDING_EVENT,
    ON_BEFORE_QUESTION_EVENT,
    ON_QUESTION_POSTED_EVENT,
    ON_AFTER_QUESTION_EVENT,
    ON_BREAK_STARTING_EVENT,
    ON_SNACK_BREAK_EVENT,
    ON_BREAK_ENDING_EVENT,
}