const swaggerJsDoc = require('swagger-jsdoc');
const swaggerUI = require('swagger-ui-express');

module.exports = function (app) {

  const options = {
    definition: {
      openapi: "3.0.3", // present supported openapi version
      info: {
        title: "Simple Todos API", // short title.
        description: "A simple todos API", //  desc.
        version: "1.0.0", // version number
        contact: {
          name: "Maina, Stephen", // your name
          email: "m41na@yahoo.com", // your email
          url: "akilisha.org", // your website
        },
      },
      servers: [
        {
          url: 'http://localhost:4000/todos',
          "description": "development server"
        },
      ],
      components: {
        schemas: {
          Todo: {
            type: "object",
            required: ["title"],
            properties: {
              id: {
                type: "string",
                description: "The autogenerated id of the todo item"
              },
              title: {
                type: "string",
                description: "The todo title"
              },
              done: {
                type: "boolean",
                description: "tells whether the task is completed"
              }
            },
            example: {
              id: "khk123lk3",
              title: "make dinner",
              done: false
            }
          }
        },
        reponses: {
          NotFound: {
            description: "Entity not found"
          },
          IllegalInput: {
            description: "Missing inputs in request"
          }
        },
        securitySchemes: {
          api_key: {
            type: "apiKey",
            name: "api_key",
            in: "header"
          },
        },
      },
      paths: {
        "/all": {
          get: {
            description: "Returns all todo items available",
            responses: {
              200: {
                description: "A list of todo items",
                content: {
                  "application/json": {
                    schema: {
                      type: "array",
                      items: {
                        $ref: "#/components/schemas/Todo"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "/": {
          post: {
            description: "Create a new todo item",
            responses: {
              200: {
                description: "A list of the updated todo items",
                content: {
                  "application/json": {
                    schema: {
                      type: "array",
                      items: {
                        $ref: "#/components/schemas/Todo"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    apis: ["./routes/*.js"],
  };

  const specs = swaggerJsDoc(options);

  app.use("/api-docs", swaggerUI.serve, swaggerUI.setup(specs))
}